### ISSUE TITLE
SharedLocalizer

### ISSUE THREAD

**Issue by jimmy84** [WormieCorp/Localization.AspNetCore.TagHelpers#12]
Hi,

Is there any plan for SharedLocalizer?

Perhaps something like 
```
<h1>@SharedLocalizer["Hello!"]</h1>
```
to 
```
<h1 sharedlocalize>Hello!</h1>
```

**Comment by AdmiringWorm** [comment]
I'm not completely sure what you mean.

if you mean to have a previously instantiated localizer that you can use as an attribute, then I don't think that is possible (or at least I don't know how)

**Comment by AdmiringWorm** [comment]
However you can specify a shared name (if the base localizer supports it) by using the following:
```html
<h1 localize name="SharedName">Hello!</h1>
```
which then passes that name along with the application name to the `IHtmlLocalizerFactory.Create` method instead of generating the name from the view.

**Comment by AdmiringWorm** [comment]
Appologize, I remembered wrong it wasn't
```html
<h1 localize name="SharedName">Hello!</h1>
```

it was
```html
<h1 localize resource-name="SharedName">Hello!</h1>
```

**Comment by jimmy84** [comment]
Getting close, but don't really work.

I am referring to the @SharedLocalizer as per shown in [Globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) which call the dummy class SharedResource

```
@using Microsoft.AspNet.Mvc.Localization
@using Localization.StarterWeb.Services

@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    ViewData["Title"] = Localizer["About"];
}
<h2>@ViewData["Title"].</h2>

<h1>@SharedLocalizer["Hello!"]</h1>
```

**Comment by AdmiringWorm** [comment]
Currently the only way to make this work with the current library would be to call the localized tag helper with one of the following:
I'm guessing the SharedResource class is located in the services directory:
```html
<h1 localize resource-name="Services/SharedLocalized">Hello</h1>
```

or with:
```html
@using Localization.StarterWeb.Services

<h1 localize resource-type="@typeof(SharedResource)">Hello</h1>
```

If neither of those work, then that would be a bug I didn't notice when initially creating a library.

As I mentioned previously, having a tag helper that dynamically uses a name of an already initialized isn't possible as far as I know.

I also finally got around to create some docs for the different attributes available for the localize element/attribute which you can take a look at on the wiki:
https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/wiki/Localize-using-Tag
that wiki pages is for the localize element, but the same attributes can be used with the localize attribute.

**Comment by jimmy84** [comment]
SharedResource is just a dummy class on the default namespace

```
namespace Localization.StarterWeb
{
    public class SharedResource
    {
    }
}
```

So by doing as below will work.

`<h1 localize resource-type="@typeof(SharedResource)">Hello</h1>`

Thanks!
