### ISSUE TITLE
Localization TagHelper can't support the default language.

### ISSUE THREAD

**Issue by zredb** [WormieCorp/Localization.AspNetCore.TagHelpers#16]
Hi,
     In aspnetcore, IStringLocalizer doesn't require you to store the default language strings in a resource file.
but if I use the TagHelper, when i delete the the default language resx file( assume is .en.resx), the language always display as norsk for sample project. would you tell me how to avoid this issue? because add a language resource is tedious.

**Comment by AdmiringWorm** [comment]
Unfortunately that was a problem I also found when creating the sample project, and the main reason for why the `.en.resx` files is included in the project.

It seemed to me that the resx provider for `IStringLocalizer` caches the strings the webpage was initially displayed in, and if no matching resx file is found when changing the language back to english it just uses the already cached strings.

I've yet to find a workaround for it, but I noticed the localization library have been updated after the sample project was created, so you could try updating `Microsoft.AspNetCore.Localization` located in the [csproj file](https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/blob/master/src/Localization.Demo/Localization.Demo.csproj#L25) to version `1.1.2` and see if that works.

**Comment by zredb** [comment]
Hi AdmiringWorm,
     the package Microsoft.AspNetCore.Localization has been updated to 1.1.3, but the issue still exist.

**Comment by AdmiringWorm** [comment]
@zredb Unfortunately, int that case I have no idea of to get around the issue of needing to create a resource file for the default language.

**Comment by AdmiringWorm** [comment]
Since this issue isn't related to the library itself, and it have been open for quite a while now I'm afraid I'll be closing this issue now.
