### ISSUE TITLE
Support for Resource with HTML value

### ISSUE THREAD

**Issue by KiarashS** [WormieCorp/Localization.AspNetCore.TagHelpers#23]
Whats about localization for resources value which include HTML tags?

**Comment by AdmiringWorm** [comment]
This can already be done, by disabling the html encoding for tags:
see [the wiki](https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/wiki/Localize-using-Tag#disabling-html-encoding-of-text-to-be-localized) for 1 example on how.

**Comment by KiarashS** [comment]
@AdmiringWorm Whats about resources which include HTML tags as their keys(names)?

**Comment by AdmiringWorm** [comment]
That should work as well, but just in case I mistake what you're asking for, could you give me a small example?

**Comment by KiarashS** [comment]
@AdmiringWorm 

![localization](https://user-images.githubusercontent.com/1054134/38515257-f2dd814e-3c48-11e8-9333-e3184d1f6585.JPG)


```
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
}
Message @ViewData["Message"]
<br/>
@Localizer["<b>Hello</b><i> {0}</i>", "Man"]
<br/>
@Localizer["About Title"]

```

**Comment by AdmiringWorm** [comment]
@KiarashS 
the following would be the equivalent to your example:

```html
Message @ViewData["Message"]
<br />
<localize html="true">
<parameter>Man</parameter>
<b>Hello</b><i> {0}</i>"
</localize>
<br />
<localize>About Title</localize>
```

Or if you want to reuse the same `IViewLocalizer`
```html
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

Message @ViewData["Message"]
<br />
<localize html="true" localizer="@Localizer">
<parameter>Man</parameter>
<b>Hello</b><i> {0}</i>"
</localize>
<br />
<localize localizer="@Localizer">About Title</localize>
```
