### ISSUE TITLE
Cache IHtmlLocalizer in views

### ISSUE THREAD

**Issue by mhmd-azeez** [WormieCorp/Localization.AspNetCore.TagHelpers#25]
## Expected Behavior
Instances of `IHtmlLocalizers` are created only once per razor view, if the razor view contains other child views, then each view gets its own `IHtmlLocalizer` instance (Layouts, Partial Views..).

## Current Behavior
A new instance of `IHtmlLocalizer` is created for each `GenericLocalizeTagHelper`.

## Possible Solution
We can cache `IHtmlLocalizers` in `ViewContext.ViewData` and only asking for a new instance when there isn't a cached instance. We need to change `GenericLocalizeTagHelper.cs` like so:

```csharp
public override void Init(TagHelperContext context)
{
  var key = "CachedLocalizerFor" + ViewContext.ExecutingFilePath;

  if (Localizer is null)
  {
    if (ViewContext.ViewData.ContainsKey(key))
    {
      Localizer = ViewContext.ViewData[key] as IHtmlLocalizer;
    }
    else
    {
      Localizer = localizerFactory.ResolveLocalizer(ViewContext, applicationName, Type, Name);
      ViewContext.ViewData[key] = Localizer;
    }
  }

  if (!SupportsParameters)
  {
    return;
  }

  // The rest of the method hasn't changed
}
```

As far as I know, that's the only change that's needed, I can send a PR if you don't have the time.

**Note:** We append the name of the current view to make sure that the partial views get their own instance of `IHtmlLocalizer`, otherwise they won't be localized correctly.

## Context
This might help make the Tag Helper faster without needing any changes by the user. Related to #13

**Comment by mhmd-azeez** [comment]
Btw, thank you for making the project build without anything special 👏. It's nice to see clean Open source projects like this one

**Comment by AdmiringWorm** [comment]
@encrypt0r this sounds like a good idea to me, I would love a PR to add this enhancement.
Honestly, this was never even in my thoughts, as I believe the IHtmlFactory implementation usually caches the localizer itself (I may be naive by thinking this though).

> Btw, thank you for making the project build without anything special 👏. It's nice to see clean Open source projects like this one

Your welcome, I'm glad you like it

**Comment by AdmiringWorm** [comment]
btw, do note that I require a CLA to be signed for opened PR's. You'll be notified automatically of this.

**Comment by AdmiringWorm** [comment]
I'll release a new version this coming weekend with the changes you provided.

Thanks again for providing them.

/cc @encrypt0r

**Comment by AdmiringWorm** [comment]
The new release is now available on nuget.org

https://www.nuget.org/packages/Localization.AspNetCore.TagHelpers/0.5.0
